[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npx prisma migrate deploy"
]

[start]
cmd = "cd backend && node server.js"
